version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "updating lambda function..."
      - aws lambda update-function-code --function-name github-to-lambda --zip-file fileb://github-to-lambda.zip
artifacts:
  files:
    - '**/*'
